print("--- Path Transformer ---")
file_path = input("Enter the path: ")
old_folder = input("Enter the old folder: ")
new_folder = input("Enter the new folder: ")
file_path = file_path.strip().replace(old_folder,new_folder)
upper_path = file_path.upper()
print(f"\"{upper_path}\"")
print(file_path.count("\\"))
print(upper_path.endswith(".TXT"))
